# Generated by Django 4.1.7 on 2023-03-31 06:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('profile_pic', models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Profile Picture')),
                ('comment', models.CharField(max_length=250)),
                ('date', models.DateField(default=datetime.datetime(2023, 3, 31, 6, 44, 14, 942365, tzinfo=datetime.timezone.utc), verbose_name='date commented')),
            ],
        ),
    ]
