# Generated by Django 4.2.3 on 2023-08-06 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0012_alter_comments_date_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 5, 27, 14, 129309, tzinfo=datetime.timezone.utc), verbose_name='date commented'),
        ),
    ]
