# Generated by Django 4.2.3 on 2023-08-06 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0014_products_file_alter_comments_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='priceUsd',
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 11, 42, 34, 63276, tzinfo=datetime.timezone.utc), verbose_name='date commented'),
        ),
    ]
