# Generated by Django 4.2.3 on 2023-08-06 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0015_remove_products_priceusd_products_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bootstrap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='css',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='django',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='html',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='js',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='php',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='tailwind',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 13, 2, 34, 973411, tzinfo=datetime.timezone.utc), verbose_name='date commented'),
        ),
    ]
