# Generated by Django 4.2.3 on 2023-08-06 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0016_products_bootstrap_products_css_products_django_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('clicked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 13, 51, 0, 254787, tzinfo=datetime.timezone.utc), verbose_name='date commented'),
        ),
    ]
