# Generated by Django 4.2.3 on 2023-08-06 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0017_click_alter_comments_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Click',
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 14, 4, 8, 396344, tzinfo=datetime.timezone.utc), verbose_name='date commented'),
        ),
    ]
