# Generated by Django 4.2.3 on 2023-08-06 15:05

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0019_anonymousclick_has_clicked_alter_comments_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousClick',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='user',
        ),
        migrations.AddField(
            model_name='counter',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 15, 5, 5, 51479, tzinfo=datetime.timezone.utc), verbose_name='date commented'),
        ),
    ]
