# Generated by Django 4.2.3 on 2023-08-06 15:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('me', '0020_delete_anonymousclick_remove_counter_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='uuid',
        ),
        migrations.AddField(
            model_name='counter',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 15, 6, 58, 27336, tzinfo=datetime.timezone.utc), verbose_name='date commented'),
        ),
    ]
