# Generated by Django 4.2.3 on 2023-08-07 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0021_remove_counter_ip_address_remove_counter_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 7, 12, 25, 7, 473904, tzinfo=datetime.timezone.utc), verbose_name='date commented'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='profile_pic',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
